# DATA CLEANING AND PREPROCESSING
### Handling Missing Data in Pandas
Handling missing data is a crucial part of data cleaning in data analytics and data science. 

Missing values can affect the accuracy of analysis and machine learning models.

Pandas provides powerful functions to detect, remove, and fill missing values, such as:

+ isnull() – Detect missing values.
+ dropna() – Remove missing values.
+ fillna() – Fill missing values.
#### Creating a DataFrame

In [1]:
import pandas as pd
import numpy as np

data = {
    'name': ['alice', 'bob', 'charlie', 'david'],
    'age': [25, np.nan, 27, 32],
    'city': ['london', 'usa', 'america', np.nan]
}

df = pd.DataFrame(data)

print(df)

      name   age     city
0    alice  25.0   london
1      bob   NaN      usa
2  charlie  27.0  america
3    david  32.0      NaN

Here, NaN represents a missing value.

### Detecting Missing Values Using isnull()
The isnull() function returns a DataFrame of True and False values, indicating whether each value is missing.

### Syntax:

In [2]:
print(df.isnull())

    name    age   city
0  False  False  False
1  False   True  False
2  False  False  False
3  False  False   True

### Explanation:
+ True indicates a missing value.
+ False indicates a non-missing value.
####  Removing Missing Values Using dropna()
The dropna() function removes rows or columns containing missing values.

#####  Drop rows containing any missing values

In [3]:
print(df.dropna())

      name   age     city
0    alice  25.0   london
2  charlie  27.0  america

### Explanation: 
Rows containing at least one missing value are removed by default.

####  Drop columns containing missing values

In [4]:
print(df.dropna(axis=1))

      name
0    alice
1      bob
2  charlie
3    david

### Explanation:
The axis=1 parameter removes columns containing missing values. The axis=0 default removes rows.

####  Filling Missing Values Using fillna()
The fillna() function replaces missing values with specified values.

#####  Fill missing values with zero

In [5]:
print(df.fillna(0))

      name   age     city
0    alice  25.0   london
1      bob   0.0      usa
2  charlie  27.0  america
3    david  32.0        0

This replaces all missing values with 0.

###  Fill missing values with a string

In [6]:
print(df.fillna("unknown"))

      name      age     city
0    alice     25.0   london
1      bob  unknown      usa
2  charlie     27.0  america
3    david     32.0  unknown

This replaces missing values with the string "unknown".

Note: Filling numeric columns with strings may change the data type of those columns.

### Fill missing numerical values with the column mean

The mean is the average of the available numerical values.

In [7]:
df['age'] = df['age'].fillna(df['age'].mean())
print(df)

      name   age     city
0    alice  25.0   london
1      bob  28.0      usa
2  charlie  27.0  america
3    david  32.0      NaN

### Explanation:

The mean age is calculated as:

Mean = (25 + 27 + 32) / 3 = 28

The missing age value is replaced with 28.0. The missing city value remains unchanged.

###  Converting Data to Numeric Format
Sometimes numerical data may be stored as text. The pd.to_numeric() function converts values into numeric format.

In [9]:
import pandas as pd
import numpy as np

data = {
    'name': ['alice', 'bob', 'charlie', 'david'],
    'age': [25, np.nan, 27, 32],
    'city': ['london', 'usa', 'america', np.nan]
}

df = pd.DataFrame(data)
df['age'] = pd.to_numeric(
    df['age'],
    errors='coerce'
)
df['age'] = df['age'].fillna(df['age'].mean())
print(df)

      name   age     city
0    alice  25.0   london
1      bob  28.0      usa
2  charlie  27.0  america
3    david  32.0      NaN

### Explanation:

errors='coerce' converts invalid numerical values into NaN.

This helps identify invalid or missing numerical data before preprocessing.
### Saving the Cleaned Data to a CSV File
After cleaning the data, it can be saved to a CSV file using to_csv().

In [11]:
import pandas as pd
import numpy as np

data = {
    'name': ['alice', 'bob', 'charlie', 'david'],
    'age': [25, np.nan, 27, 32],
    'city': ['london', 'usa', 'america', np.nan]
}

df = pd.DataFrame(data)
df['age'] = pd.to_numeric(
    df['age'],
    errors='coerce'
)
df['age'] = df['age'].fillna(df['age'].mean())
df.to_csv('output.csv',index=True)

### Explanation:

output.csv is the name of the output file.

index=False prevents Pandas from saving the row index as an additional column.

The saved CSV file can be opened in Excel or imported into another Jupyter Notebook.

## Handling Duplicate Data in Pandas
Duplicate data refers to rows that appear more than once in a dataset. Duplicate records can affect the accuracy of data analysis and should be identified and handled during data preprocessing.

Pandas provides two important functions for handling duplicates:

+ duplicated() – Identifies duplicate rows.
+ drop_duplicates() – Removes duplicate rows.
##  duplicated() Function
The duplicated() function identifies duplicate rows and returns a Boolean Series. It returns True for duplicate occurrences and False for the first occurrence by default.

### Syntax:

df.duplicated(subset=None, keep='first')

Parameters:

+ subset: Specifies the column or columns used to identify duplicates.
+ keep='first': Marks later duplicate occurrences as True.
+ keep='last': Marks earlier duplicate occurrences as True.
+ keep=False: Marks all duplicate occurrences as True.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "a": [1, 2, 2, 3, 3, 3],
    "b": ["a", "b", "b", "c", "c", "c"]
})

print(df.duplicated())

0    False
1    False
2     True
3    False
4     True
5     True
dtype: bool

#### Explanation:
+ Row 0 is not a duplicate.
+ Row 1 is the first occurrence of the values (2, 'b').
+ Row 2 is a duplicate of row 1.
+ Row 3 is the first occurrence of the values (3, 'c').
+ Rows 4 and 5 are duplicates of row 3.
## drop_duplicates() Function
The drop_duplicates() function removes duplicate rows from a DataFrame.

### Syntax:

In [2]:
df.drop_duplicates(
    subset=None,
    keep='first',
    inplace=False
)

   a  b
0  1  a
1  2  b
3  3  c

#### Parameters:
+ subset: Specifies the columns to check for duplicates.
+ keep='first': Keeps the first occurrence.
+ keep='last': Keeps the last occurrence.
+ inplace=False: Returns a new DataFrame without changing the original DataFrame.
### Example:

In [3]:
import pandas as pd

df = pd.DataFrame({
    "a": [1, 2, 2, 3, 3, 3],
    "b": ["a", "b", "b", "c", "c", "c"]
})

print(df.drop_duplicates())

   a  b
0  1  a
1  2  b
3  3  c

### Explanation:

The duplicate rows are removed, and the first occurrence of each unique row is retained. The original row index is preserved.

####  Adding and Removing Columns and Rows in Pandas
Pandas allows users to add, modify, and remove columns and rows in a DataFrame. These operations are useful for preparing and organizing data for analysis.

### Creating a DataFrame

In [4]:
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": ["a", "b", "c"]
})

print(df)

   A  B
0  1  a
1  2  b
2  3  c

### Adding a Column with a Single Value
A new column can be added by assigning a single value to a new column name. Pandas repeats that value for every row.

#### Example:

In [5]:
df["C"] = 10
print(df)

   A  B   C
0  1  a  10
1  2  b  10
2  3  c  10

### Explanation: 
The value 10 is assigned to every row in the new column C.

#### Adding a Column from a List
A new column can also be added using a list of values. The number of values should match the number of rows in the DataFrame.

### Example:

In [6]:
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": ["a", "b", "c"]
})

df["C"] = 10
df["D"] = [100, 200, 300]

print(df)

   A  B   C    D
0  1  a  10  100
1  2  b  10  200
2  3  c  10  300

### Explanation: 
Column D is created using the list [100, 200, 300].

### Adding a Column Based on an Existing Column
A new column can be calculated using values from an existing column.

#### Example:

In [7]:
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": ["a", "b", "c"]
})

df["C"] = 10
df["D"] = [100, 200, 300]
df["E"] = df["A"] * 2

print(df)

   A  B   C    D  E
0  1  a  10  100  2
1  2  b  10  200  4
2  3  c  10  300  6

### Explanation: 
Column E is calculated by multiplying every value in column A by 2.

### Example:

Row 0: 1 × 2 = 2

Row 1: 2 × 2 = 4

Row 2: 3 × 2 = 6
### Removing a Column
The drop() function can remove a column by specifying its name and setting axis=1.

Example:

In [8]:
df = df.drop("C", axis=1)
print(df)

   A  B    D  E
0  1  a  100  2
1  2  b  200  4
2  3  c  300  6

### Explanation: 
The column C is removed from the DataFrame. The original DataFrame remains unchanged unless the result is reassigned or inplace=True is used.

## Removing a Row
A row can be removed by specifying its index and setting axis=0.

### Example:

In [9]:
df = df.drop(1, axis=0)

print(df)

   A  B    D  E
0  1  a  100  2
2  3  c  300  6

### Explanation: 
The row with index 1 is removed from the DataFrame.

# Sorting Data in Pandas
Sorting is an important operation in data cleaning and preprocessing. It helps arrange data in a specific order, making datasets easier to read, analyze, and compare.

Pandas provides two important sorting functions:

+ sort_values() – Sorts a DataFrame or Series based on values.
+ sort_index() – Sorts a DataFrame or Series based on index labels.
###  sort_values() Function
The sort_values() function sorts a DataFrame according to the values in one or more columns.

#### Syntax:
df.sort_values(by='column_name', ascending=True)
##### Parameters:

+ by: Specifies the column name used for sorting.
+ ascending=True: Sorts values in ascending order.
+ ascending=False: Sorts values in descending order.
### Example:

In [10]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 20]
})

print(df.sort_values(by='Age'))

      Name  Age
2  Charlie   20
0    Alice   25
1      Bob   30

#### Explanation:

The DataFrame is sorted according to the Age column in ascending order, from the smallest age to the largest age.

#### Sorting in descending order:

In [11]:
print(df.sort_values(by='Age', ascending=False))

      Name  Age
1      Bob   30
0    Alice   25
2  Charlie   20

#### Explanation:
The ages are arranged from the largest to the smallest.

## sort_index() Function
The sort_index() function sorts a DataFrame or Series according to its index labels.

#### Syntax:
df.sort_index(axis=0, ascending=True)
#### Parameters:
+ axis=0: Sorts rows according to their index labels. This is the default.
+ axis=1: Sorts columns according to their column labels.
+ ascending=True: Sorts in ascending order.
+ ascending=False: Sorts in descending order.
### Example:

In [12]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 20]
}, index=[2, 0, 1])

print(df.sort_index())

      Name  Age
0      Bob   30
1  Charlie   20
2    Alice   25

#### Explanation:
The rows are arranged according to their index labels in ascending order: 0, 1, and 2.

Notice that the row data remains together; only the order of the rows changes.

Sorting index labels in descending order:

In [13]:
print(df.sort_index(ascending=False))

      Name  Age
2    Alice   25
1  Charlie   20
0      Bob   30

#### Explanation:
The rows are arranged from the highest index label to the lowest.

# Filtering and Subsetting in Pandas
### Selecting Columns
   
+ Single column — returns a Series.

df['column_name']

+ Multiple columns — returns a DataFrame.

df[['col1', 'col2']]
###  Subsetting Rows (Filtering)
Filter rows based on a condition.

In [1]:
import pandas as pd
df=pd.read_csv("pd2(2).csv")
df

        Name  Age Gender Country
0        anu   20      m   paris
1       achu   25      f  europe
2       babu   21      m     uae
3      kichu   24      m  dubali
4      alice   22      f   india
5    charlie   26      m   delhi
6       paru   24      f     tvm
7      evana   25      f     ekm
8  evanshika   21      f     pkd
9       banu   25      f  kollam

In [3]:
import pandas as pd
df=pd.read_csv("pd2(2).csv")
df[df['Age'] > 23]

      Name  Age Gender Country
1     achu   25      f  europe
3    kichu   24      m  dubali
5  charlie   26      m   delhi
6     paru   24      f     tvm
7    evana   25      f     ekm
9     banu   25      f  kollam

This selects all rows where the Age is greater than 23.

### Filtering with Multiple Conditions
Use & for AND and | for OR.

In [6]:
import pandas as pd
df=pd.read_csv("pd2(2).csv")
df[(df['Age'] > 21) & (df['Gender'] == 'm')]

      Name  Age Gender Country
3    kichu   24      m  dubali
5  charlie   26      m   delhi

This selects rows where Age is greater than 21 and Gender is m.
### Using .loc[] for Filtering and Subsetting
#### Syntax:

df.loc[rows, columns]

Select rows where Age is greater than 24.

In [7]:
import pandas as pd
df=pd.read_csv("pd2(2).csv")
df.loc[df['Age'] > 24]

      Name  Age Gender Country
1     achu   25      f  europe
5  charlie   26      m   delhi
7    evana   25      f     ekm
9     banu   25      f  kollam

Filter rows and select specific columns.

In [10]:
import pandas as pd
df=pd.read_csv("pd2(2).csv")
df.loc[df['Age'] > 24, ['Name', 'Age']]

      Name  Age
1     achu   25
5  charlie   26
7    evana   25
9     banu   25

### Using .iloc[] for Selecting by Position
#### Syntax:
df.iloc[rows, columns]

Select the first three rows.

In [11]:
df.iloc[0:3]

   Name  Age Gender Country
0   anu   20      m   paris
1  achu   25      f  europe
2  babu   21      m     uae

Select the first three rows and columns at positions 1 and 2.

In [12]:
df.iloc[0:3, 1:3]

   Age Gender
0   20      m
1   25      f
2   21      m

Note: .iloc[] uses integer positions, starting from zero. The ending position is excluded.

## Filtering with .isin()
Select rows where the country belongs to a specified list.

In [15]:
df[df['Country'].isin(['uae', 'tvm'])]

   Name  Age Gender Country
2  babu   21      m     uae
6  paru   24      f     tvm


This returns rows where the country is either uae or tvm.

## Filtering String Columns with String Methods
Contains a substring:

In [17]:
df[df['Name'].str.contains('bu')]

   Name  Age Gender Country
2  babu   21      m     uae

Selects names containing bu.

Starts with a character:

In [19]:
df[df['Name'].str.startswith('a')]

    Name  Age Gender Country
0    anu   20      m   paris
1   achu   25      f  europe
4  alice   22      f   india

Selects names starting with a.

Ends with a character:

In [18]:
df[df['Name'].str.endswith('e')]

      Name  Age Gender Country
4    alice   22      f   india
5  charlie   26      m   delhi

Selects names ending with e.

# Filtering Data Using the .query() Method
The .query() method in Pandas is used to filter rows from a DataFrame based on specified conditions. It makes filtering easier and more readable.
### Syntax

df.query("condition")
#### Example: 
Filtering by Age and Gender

In [6]:
import pandas as pd
df = pd.read_csv("pd2(2).csv")
result = df.query("Age >= 20 and Gender == 'm'")
print(result)

      Name  Age Gender Country
0      anu   20      m   paris
2     babu   21      m     uae
3    kichu   24      m  dubali
5  charlie   26      m   delhi

### Explanation:

age >= 20 selects people whose age is 20 or above.

gender == 'm' selects male records.

and combines both conditions.

Only rows satisfying both conditions will be displayed.

# Aggregation and Grouping Using groupby()
The groupby() function is one of the most powerful features of Pandas.

It allows you to:
+ Split data into groups.
+ Apply a function to each group.
+ Combine the results into a new output.
### Syntax

df.groupby('column_name')

The groupby() function returns a GroupBy object, which can be used for aggregation and transformation.

In [7]:
import pandas as pd
df = pd.read_csv("pd3(2).csv")
df

  department employee  salary
0      sales    alice   50000
1      sales      bob   55000
2         hr  charlie   60000
3         hr    david   58000
4         it      eva   75000
5         it    frank   72000

### Group by a Single Column
We can group the data using a single column, such as Department, and calculate the average salary.

### Python Program

In [10]:
import pandas as pd
df = pd.read_csv("pd3(2).csv")
grouped = df.groupby('department')
print(grouped['salary'].mean())

department
hr       59000.0
it       73500.0
sales    52500.0
Name: salary, dtype: float64

### Explanation:
+ groupby('Department') groups employees by department.
+ ['Salary'] selects the Salary column.
+ .mean() calculates the average salary for each department.
## Grouping Using the Sum Function
The sum() function calculates the total salary of employees in each department.

### Python Program

In [12]:
import pandas as pd
df = pd.read_csv('pd3(2).csv')
grouped = df.groupby('department')['salary'].sum()
print(grouped)

department
hr       118000
it       147000
sales    105000
Name: salary, dtype: int64

### Explanation:

The sum() function adds all the salary values belonging to each department.

## Multiple Aggregations Using agg()
The agg() function is used to perform multiple aggregation operations on a column at the same time.

For example, we can calculate:
+ Mean – Average salary.
+ Max – Highest salary.
+ Min – Lowest salary.
### Python Program

In [14]:
import pandas as pd
df = pd.read_csv('pd3(2).csv')
grouped = df.groupby('department')['salary'].agg(
    ['mean', 'max', 'min']
)
print(grouped)

               mean    max    min
department
hr          59000.0  60000  58000
it          73500.0  75000  72000
sales       52500.0  55000  50000

### Explanation:
+ mean calculates the average salary.
+ max returns the highest salary.
+ min returns the lowest salary.
All three operations are performed together.

## Group by Multiple Columns
Pandas also allows us to group data using more than one column.

For example, we can group employees by both Department and Employees.

#### Python Program

In [16]:
import pandas as pd
df = pd.read_csv('pd3(2).csv')
result = df.groupby(
    ['department', 'employee']
)['salary'].sum()
print(result)

department  employee
hr          charlie     60000
            david       58000
it          eva         75000
            frank       72000
sales       alice       50000
            bob         55000
Name: salary, dtype: int64

### Explanation:
+ Department groups employees according to their department.
+ Employees creates additional groups based on employee names.
+ sum() calculates the total salary for each group.
## Using agg() with Custom Functions
The agg() function also allows us to provide custom names for aggregation results.

For example, we can calculate total salary, average salary, and number of employees in each department.

#### Python Program

In [18]:
import pandas as pd
df = pd.read_csv('pd3(2).csv')
result = df.groupby('department').agg(
    total_salary=('salary', 'sum'),
    average_salary=('salary', 'mean'),
    num_employees=('employee', 'count')
)
print(result)

            total_salary  average_salary  num_employees
department
hr                118000         59000.0              2
it                147000         73500.0              2
sales             105000         52500.0              2

### Explanation:
+ total_salary calculates the total salary of each department.
+ average_salary calculates the average salary.
+ num_employees counts the number of employees in each department.